### ISSUE TITLE
 Error, call sgx_create_enclave for PCE fail [load_pce], SGXError:2006. Error in sgx_qe_get_target_info. 0xe00d

### ISSUE THREAD

**Issue by imuzi** [on-premise-signal/signal-setup-guide#1]
I use bare-metal server from Vultr.com,and followed every step. tried so many times. still get the same error when generate PCK. where did i miss? 
BTW,does PCK Certificate must be generate to run the server or we can use  other way to get what we need？

**Comment by konglomerat-id** [comment]
Hi @imuzi ,

no, my team found that we don't need any PCK... 

You can follow my post:
https://community.signalusers.org/t/guide-deploy-signal-server-v2-xx-cds-sgx/8331/41?u=konglomerat
